# please keep this alphabetized
linters:
  enable:
    - asciicheck
    - contextcheck
    - forcetypeassert
    - gocritic
    - godot
    - gofmt
    - goimports
    - misspell
    - revive
    - stylecheck

run:
  tests: true
  timeout: 10m

linters-settings:
  goimports:
    local-prefixes: "github.com/klueska/kind-with-gpus-examples"

issues:
  include:
    - EXC0012  # EXC0012 revive: Annoying issue about not having a comment. The rare codebase has such comments
    - EXC0014  # EXC0014 revive: Annoying issue about not having a comment. The rare codebase has such comments
